#######################################
#----------------Signup---------------#
#######################################
POST http://localhost:5000/signup HTTP/1.1
Content-Type: application/json

{ 
  "email": "anime@gmail.com",
  "password": "ffffff",
  "passwordCheck": "ffffff",
  "displayName": "Otaku"
}

#######################################
#----------------Login---------------#
#######################################
POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json

{ 
  "email": "anime@gmail.com",
  "password": "ssssss"
}

#######################################
#-----------Verify Token---------------#
#######################################
POST http://localhost:5000/verifyToken HTTP/1.1
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMzNjMzNmZmQ3NWU4MDAwOGVmYmM0ZSIsImlhdCI6MTU5NzIyNzg4M30.5kpXtUJT382dHKRNFdsnKvaD57YTJpwMsASMTTrKAM8

