#######################################
#---------Get Loggedin User-----------#
#######################################
GET http://localhost:5000/users/ HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMjJiYzU4OGU5MDZkMTAwNGNmYTY1MiIsImlhdCI6MTU5NjI0Mzc4NX0.o18Xl57qV8uhBnnypE5G3x38nY7inr7Q-ya69mwVkzQ



#######################################
#-----------Update Profile------------#
#######################################
PUT http://localhost:5000/users/updateProfile HTTP/1.1
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMjJiYzU4OGU5MDZkMTAwNGNmYTY1MiIsImlhdCI6MTU5NjI0Mzc4NX0.o18Xl57qV8uhBnnypE5G3x38nY7inr7Q-ya69mwVkzQ

{
  "email": "foo@gmail.com",
  "password": "password"
}



#######################################
#--------------All Users--------------#
#######################################
GET http://localhost:5000/users/all HTTP/1.1
